version: '3.8'

services:
  # elasticsearch:
  #   image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
  #   environment:
  #     - 'ELASTIC_PASSWORD=${ELASTIC_PASSWORD}'
  #     - 'discovery.type=single-node'
  #     - 'xpack.security.enabled=false'
  #   ports:
  #     - '9200'
  #     - '9300'

  backend:
    build:
      context: ./backend
    volumes:
      - .:/hiretop_backend_volume
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - hiretop_db

  hiretop_db:
    image: postgres
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hiretop_db
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
    ports:
      - 5432:5432

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 3000:3000

  # maildev:
  #   image: maildev/maildev
  #   restart: always
  #   environment:
  #     - TZ=Africa/Lagos
  #     - MAILDEV_WEB_PORT=1080
  #     - MAILDEV_SMTP_PORT=1025
  #   ports:
  #     - "1080:1080"
  #     - "1025:1025"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "1m"

  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - MINIO_ROOT_USER=${MINIO_USER}
  #     - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
  #   volumes:
  #     - minio-data:/data

volumes:
  db-data:
  minio-data: